{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0e6b235f",
   "metadata": {},
   "source": [
    "# Assignment 12"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3a69990d",
   "metadata": {},
   "source": [
    "## Date : 13/02/2023"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "15b1c1ca",
   "metadata": {},
   "source": [
    "#### Q1. Explain why we have to use the Exception class while creating a Custom Exception."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "16365967",
   "metadata": {},
   "source": [
    "#### Answer\n",
    "In Python, creating custom exceptions is often done by creating a new class that inherits from the built-in Exception class. Here are a few reasons why using the Exception class as a base for our custom exceptions is a good practice:\n",
    "\n",
    "Consistent behavior: The Exception class is the base class for all built-in exceptions in Python, so by inheriting from it, our custom exception class will behave consistently with other exceptions in the language. For example, it will be caught by a try...except block that catches the Exception class or any of its subclasses.\n",
    "\n",
    "Built-in functionality: The Exception class provides several built-in methods that are useful for handling exceptions, such as __str__() to convert the exception to a string representation, args to retrieve the exception message, and with_traceback() to associate the exception with a traceback. By inheriting from the Exception class, our custom exception class can also have access to these methods, which can be helpful for debugging and logging.\n",
    "\n",
    "Clarity and organization: By using the Exception class as a base for our custom exception class, we make it clear to other developers that this class is intended to represent an exceptional situation in our code. It also helps to organize and group related exceptions together in a hierarchy, which can make it easier to understand and maintain a codebase over time.\n",
    "\n",
    "Overall, using the Exception class as a base for our custom exception class in Python helps to ensure consistent behavior, provides access to built-in functionality, and improves clarity and organization in our code."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "79d583d8",
   "metadata": {},
   "source": [
    "#### Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0c29b3cc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'BaseException'>\n",
      "    <class 'Exception'>\n",
      "        <class 'TypeError'>\n",
      "            <class 'decimal.FloatOperation'>\n",
      "            <class 'email.errors.MultipartConversionError'>\n",
      "        <class 'StopAsyncIteration'>\n",
      "        <class 'StopIteration'>\n",
      "        <class 'ImportError'>\n",
      "            <class 'ModuleNotFoundError'>\n",
      "                <class 'setuptools._vendor.importlib_metadata.PackageNotFoundError'>\n",
      "                <class 'importlib_metadata.PackageNotFoundError'>\n",
      "            <class 'zipimport.ZipImportError'>\n",
      "        <class 'OSError'>\n",
      "            <class 'ConnectionError'>\n",
      "                <class 'BrokenPipeError'>\n",
      "                <class 'ConnectionAbortedError'>\n",
      "                <class 'ConnectionRefusedError'>\n",
      "                <class 'ConnectionResetError'>\n",
      "                    <class 'http.client.RemoteDisconnected'>\n",
      "            <class 'BlockingIOError'>\n",
      "            <class 'ChildProcessError'>\n",
      "            <class 'FileExistsError'>\n",
      "            <class 'FileNotFoundError'>\n",
      "            <class 'IsADirectoryError'>\n",
      "            <class 'NotADirectoryError'>\n",
      "            <class 'InterruptedError'>\n",
      "                <class 'zmq.error.InterruptedSystemCall'>\n",
      "            <class 'PermissionError'>\n",
      "            <class 'ProcessLookupError'>\n",
      "            <class 'TimeoutError'>\n",
      "            <class 'io.UnsupportedOperation'>\n",
      "            <class 'socket.herror'>\n",
      "            <class 'socket.gaierror'>\n",
      "            <class 'socket.timeout'>\n",
      "            <class 'shutil.Error'>\n",
      "                <class 'shutil.SameFileError'>\n",
      "            <class 'shutil.SpecialFileError'>\n",
      "            <class 'shutil.ExecError'>\n",
      "            <class 'shutil.ReadError'>\n",
      "            <class 'ssl.SSLError'>\n",
      "                <class 'ssl.SSLCertVerificationError'>\n",
      "                <class 'ssl.SSLZeroReturnError'>\n",
      "                <class 'ssl.SSLWantReadError'>\n",
      "                <class 'ssl.SSLWantWriteError'>\n",
      "                <class 'ssl.SSLSyscallError'>\n",
      "                <class 'ssl.SSLEOFError'>\n",
      "            <class 'urllib.error.URLError'>\n",
      "                <class 'urllib.error.HTTPError'>\n",
      "                <class 'urllib.error.ContentTooShortError'>\n",
      "            <class 'gzip.BadGzipFile'>\n",
      "        <class 'EOFError'>\n",
      "            <class 'asyncio.exceptions.IncompleteReadError'>\n",
      "        <class 'RuntimeError'>\n",
      "            <class 'RecursionError'>\n",
      "            <class 'NotImplementedError'>\n",
      "                <class 'zmq.error.ZMQVersionError'>\n",
      "                <class 'IPython.core.error.StdinNotImplementedError'>\n",
      "            <class '_frozen_importlib._DeadlockError'>\n",
      "            <class 'threading.BrokenBarrierError'>\n",
      "            <class 'concurrent.futures._base.BrokenExecutor'>\n",
      "                <class 'concurrent.futures.thread.BrokenThreadPool'>\n",
      "            <class 'asyncio.exceptions.SendfileNotAvailableError'>\n",
      "            <class 'pkg_resources.ExtractionError'>\n",
      "            <class 'setuptools.errors.RemovedCommandError'>\n",
      "            <class 'setuptools.errors.PackageDiscoveryError'>\n",
      "            <class '_pydevd_bundle.pydevd_vars.VariableError'>\n",
      "        <class 'NameError'>\n",
      "            <class 'UnboundLocalError'>\n",
      "        <class 'AttributeError'>\n",
      "            <class 'dataclasses.FrozenInstanceError'>\n",
      "        <class 'SyntaxError'>\n",
      "            <class 'IndentationError'>\n",
      "                <class 'TabError'>\n",
      "        <class 'LookupError'>\n",
      "            <class 'IndexError'>\n",
      "            <class 'KeyError'>\n",
      "                <class 'jupyter_client.kernelspec.NoSuchKernel'>\n",
      "                <class 'IPython.terminal.pt_inputhooks.UnknownBackend'>\n",
      "            <class 'encodings.CodecRegistryError'>\n",
      "        <class 'ValueError'>\n",
      "            <class 'UnicodeError'>\n",
      "                <class 'UnicodeEncodeError'>\n",
      "                <class 'UnicodeDecodeError'>\n",
      "                <class 'UnicodeTranslateError'>\n",
      "            <class 'io.UnsupportedOperation'>\n",
      "            <class 'json.decoder.JSONDecodeError'>\n",
      "            <class 'ssl.SSLCertVerificationError'>\n",
      "            <class 'binascii.Error'>\n",
      "            <class 'pygments.util.ClassNotFound'>\n",
      "            <class 'IPython.lib.clipboard.ClipboardEmpty'>\n",
      "            <class 'email.errors.MessageDefect'>\n",
      "                <class 'email.errors.NoBoundaryInMultipartDefect'>\n",
      "                <class 'email.errors.StartBoundaryNotFoundDefect'>\n",
      "                <class 'email.errors.CloseBoundaryNotFoundDefect'>\n",
      "                <class 'email.errors.FirstHeaderLineIsContinuationDefect'>\n",
      "                <class 'email.errors.MisplacedEnvelopeHeaderDefect'>\n",
      "                <class 'email.errors.MissingHeaderBodySeparatorDefect'>\n",
      "                <class 'email.errors.MultipartInvariantViolationDefect'>\n",
      "                <class 'email.errors.InvalidMultipartContentTransferEncodingDefect'>\n",
      "                <class 'email.errors.UndecodableBytesDefect'>\n",
      "                <class 'email.errors.InvalidBase64PaddingDefect'>\n",
      "                <class 'email.errors.InvalidBase64CharactersDefect'>\n",
      "                <class 'email.errors.InvalidBase64LengthDefect'>\n",
      "                <class 'email.errors.HeaderDefect'>\n",
      "                    <class 'email.errors.InvalidHeaderDefect'>\n",
      "                    <class 'email.errors.HeaderMissingRequiredValue'>\n",
      "                    <class 'email.errors.NonPrintableDefect'>\n",
      "                    <class 'email.errors.ObsoleteHeaderDefect'>\n",
      "                    <class 'email.errors.NonASCIILocalPartDefect'>\n",
      "            <class 'calendar.IllegalMonthError'>\n",
      "            <class 'calendar.IllegalWeekdayError'>\n",
      "            <class 'IPython.core.magics.code.MacroToEdit'>\n",
      "            <class 'dateutil.parser._parser.ParserError'>\n",
      "            <class 'plistlib.InvalidFileException'>\n",
      "            <class 'pkg_resources._vendor.more_itertools.more.UnequalIterablesError'>\n",
      "            <class 'pkg_resources.extern.packaging.version.InvalidVersion'>\n",
      "            <class 'pkg_resources._vendor.packaging._manylinux._ELFFileHeader._InvalidELFFileHeader'>\n",
      "            <class 'pkg_resources.extern.packaging.utils.InvalidWheelFilename'>\n",
      "            <class 'pkg_resources.extern.packaging.utils.InvalidSdistFilename'>\n",
      "            <class 'pkg_resources.extern.packaging.specifiers.InvalidSpecifier'>\n",
      "            <class 'pkg_resources.extern.packaging.markers.InvalidMarker'>\n",
      "            <class 'pkg_resources.extern.packaging.markers.UndefinedComparison'>\n",
      "            <class 'pkg_resources.extern.packaging.markers.UndefinedEnvironmentName'>\n",
      "            <class 'pkg_resources.extern.packaging.requirements.InvalidRequirement'>\n",
      "                <class 'pkg_resources.RequirementParseError'>\n",
      "            <class 'setuptools._vendor.more_itertools.more.UnequalIterablesError'>\n",
      "            <class 'setuptools._vendor.packaging._manylinux._ELFFileHeader._InvalidELFFileHeader'>\n",
      "            <class 'setuptools.extern.packaging.version.InvalidVersion'>\n",
      "            <class 'setuptools.extern.packaging.utils.InvalidWheelFilename'>\n",
      "            <class 'setuptools.extern.packaging.utils.InvalidSdistFilename'>\n",
      "            <class 'setuptools.extern.packaging.specifiers.InvalidSpecifier'>\n",
      "            <class 'setuptools.extern.packaging.markers.InvalidMarker'>\n",
      "            <class 'setuptools.extern.packaging.markers.UndefinedComparison'>\n",
      "            <class 'setuptools.extern.packaging.markers.UndefinedEnvironmentName'>\n",
      "            <class 'setuptools.extern.packaging.requirements.InvalidRequirement'>\n",
      "        <class 'AssertionError'>\n",
      "        <class 'ArithmeticError'>\n",
      "            <class 'FloatingPointError'>\n",
      "            <class 'OverflowError'>\n",
      "            <class 'ZeroDivisionError'>\n",
      "                <class 'decimal.DivisionByZero'>\n",
      "                <class 'decimal.DivisionUndefined'>\n",
      "            <class 'decimal.DecimalException'>\n",
      "                <class 'decimal.Clamped'>\n",
      "                <class 'decimal.Rounded'>\n",
      "                    <class 'decimal.Underflow'>\n",
      "                    <class 'decimal.Overflow'>\n",
      "                <class 'decimal.Inexact'>\n",
      "                    <class 'decimal.Underflow'>\n",
      "                    <class 'decimal.Overflow'>\n",
      "                <class 'decimal.Subnormal'>\n",
      "                    <class 'decimal.Underflow'>\n",
      "                <class 'decimal.DivisionByZero'>\n",
      "                <class 'decimal.FloatOperation'>\n",
      "                <class 'decimal.InvalidOperation'>\n",
      "                    <class 'decimal.ConversionSyntax'>\n",
      "                    <class 'decimal.DivisionImpossible'>\n",
      "                    <class 'decimal.DivisionUndefined'>\n",
      "                    <class 'decimal.InvalidContext'>\n",
      "        <class 'SystemError'>\n",
      "            <class 'encodings.CodecRegistryError'>\n",
      "        <class 'ReferenceError'>\n",
      "        <class 'MemoryError'>\n",
      "        <class 'BufferError'>\n",
      "        <class 'Warning'>\n",
      "            <class 'UserWarning'>\n",
      "                <class 'getpass.GetPassWarning'>\n",
      "                <class 'IPython.core.formatters.FormatterWarning'>\n",
      "                <class 'setuptools.config._apply_pyprojecttoml._WouldIgnoreField'>\n",
      "                <class 'setuptools.config.pyprojecttoml._ExperimentalProjectMetadata'>\n",
      "                <class 'setuptools.config.pyprojecttoml._InvalidFile'>\n",
      "            <class 'DeprecationWarning'>\n",
      "                <class 'IPython.core.interactiveshell.ProvisionalWarning'>\n",
      "            <class 'PendingDeprecationWarning'>\n",
      "            <class 'SyntaxWarning'>\n",
      "            <class 'RuntimeWarning'>\n",
      "                <class 'zmq.asyncio.ProactorSelectorThreadWarning'>\n",
      "                <class 'dateutil.parser._parser.UnknownTimezoneWarning'>\n",
      "                <class 'pkg_resources.PEP440Warning'>\n",
      "            <class 'FutureWarning'>\n",
      "                <class 'IPython.core.completer.ProvisionalCompleterWarning'>\n",
      "            <class 'ImportWarning'>\n",
      "            <class 'UnicodeWarning'>\n",
      "            <class 'BytesWarning'>\n",
      "            <class 'ResourceWarning'>\n",
      "            <class 'dateutil.tz.DeprecatedTzFormatWarning'>\n",
      "            <class 'setuptools._deprecation_warning.SetuptoolsDeprecationWarning'>\n",
      "                <class 'setuptools.dist.DistDeprecationWarning'>\n",
      "            <class 'pkg_resources.PkgResourcesDeprecationWarning'>\n",
      "        <class 'locale.Error'>\n",
      "        <class 'warnings._OptionError'>\n",
      "        <class 're.error'>\n",
      "        <class 'sre_parse.Verbose'>\n",
      "        <class 'runpy._Error'>\n",
      "        <class 'subprocess.SubprocessError'>\n",
      "            <class 'subprocess.CalledProcessError'>\n",
      "            <class 'subprocess.TimeoutExpired'>\n",
      "        <class 'socket._GiveupOnSendfile'>\n",
      "        <class 'zlib.error'>\n",
      "        <class '_lzma.LZMAError'>\n",
      "        <class 'shutil.RegistryError'>\n",
      "        <class 'shutil._GiveupOnFastCopy'>\n",
      "        <class 'zmq.error.ZMQBaseError'>\n",
      "            <class 'zmq.error.ZMQError'>\n",
      "                <class 'zmq.error.ContextTerminated'>\n",
      "                <class 'zmq.error.Again'>\n",
      "                <class 'zmq.error.InterruptedSystemCall'>\n",
      "            <class 'zmq.error.ZMQBindError'>\n",
      "            <class 'zmq.error.NotDone'>\n",
      "        <class 'copy.Error'>\n",
      "        <class 'struct.error'>\n",
      "        <class '_pickle.PickleError'>\n",
      "            <class '_pickle.PicklingError'>\n",
      "            <class '_pickle.UnpicklingError'>\n",
      "        <class 'pickle._Stop'>\n",
      "        <class 'tokenize.TokenError'>\n",
      "        <class 'tokenize.StopTokenizing'>\n",
      "        <class 'inspect.ClassFoundException'>\n",
      "        <class 'inspect.EndOfBlock'>\n",
      "        <class 'traitlets.traitlets.TraitError'>\n",
      "        <class 'argparse.ArgumentError'>\n",
      "        <class 'argparse.ArgumentTypeError'>\n",
      "        <class 'traitlets.config.loader.ConfigError'>\n",
      "            <class 'traitlets.config.loader.ConfigLoaderError'>\n",
      "                <class 'traitlets.config.loader.ArgumentError'>\n",
      "            <class 'traitlets.config.loader.ConfigFileNotFound'>\n",
      "        <class 'traitlets.config.configurable.ConfigurableError'>\n",
      "            <class 'traitlets.config.configurable.MultipleInstanceError'>\n",
      "        <class 'traitlets.config.application.ApplicationError'>\n",
      "        <class 'jupyter_client.localinterfaces.NoIPAddresses'>\n",
      "        <class 'concurrent.futures._base.Error'>\n",
      "            <class 'concurrent.futures._base.CancelledError'>\n",
      "            <class 'concurrent.futures._base.TimeoutError'>\n",
      "            <class 'concurrent.futures._base.InvalidStateError'>\n",
      "        <class 'binascii.Incomplete'>\n",
      "        <class 'asyncio.exceptions.TimeoutError'>\n",
      "        <class 'asyncio.exceptions.InvalidStateError'>\n",
      "        <class 'asyncio.exceptions.LimitOverrunError'>\n",
      "        <class 'asyncio.queues.QueueEmpty'>\n",
      "        <class 'asyncio.queues.QueueFull'>\n",
      "        <class 'jupyter_client.channels.InvalidPortNumber'>\n",
      "        <class '_queue.Empty'>\n",
      "        <class 'queue.Full'>\n",
      "        <class 'jupyter_client.multikernelmanager.DuplicateKernelError'>\n",
      "        <class 'tornado.util.TimeoutError'>\n",
      "        <class '_ctypes.COMError'>\n",
      "        <class 'ctypes.ArgumentError'>\n",
      "        <class 'tornado.concurrent.ReturnValueIgnoredError'>\n",
      "        <class 'tornado.gen.KeyReuseError'>\n",
      "        <class 'tornado.gen.UnknownKeyError'>\n",
      "        <class 'tornado.gen.LeakedCallbackError'>\n",
      "        <class 'tornado.gen.BadYieldError'>\n",
      "        <class 'tornado.gen.ReturnValueIgnoredError'>\n",
      "        <class 'tornado.gen.Return'>\n",
      "        <class 'pydoc.ErrorDuringImport'>\n",
      "        <class 'executing.executing.NotOneValueFound'>\n",
      "        <class 'pure_eval.utils.CannotEval'>\n",
      "        <class 'pygments.util.OptionError'>\n",
      "        <class 'bdb.BdbQuit'>\n",
      "        <class 'pdb.Restart'>\n",
      "        <class 'IPython.utils.process.FindCmdError'>\n",
      "        <class 'IPython.utils.path.HomeDirError'>\n",
      "        <class 'IPython.core.profiledir.ProfileDirError'>\n",
      "        <class 'IPython.core.error.IPythonCoreError'>\n",
      "            <class 'IPython.core.error.TryNext'>\n",
      "            <class 'IPython.core.error.UsageError'>\n",
      "            <class 'IPython.core.error.StdinNotImplementedError'>\n",
      "        <class 'IPython.core.error.InputRejected'>\n",
      "        <class 'getopt.GetoptError'>\n",
      "        <class 'pygments.filters.ErrorToken'>\n",
      "        <class 'IPython.core.prefilter.PrefilterError'>\n",
      "        <class 'IPython.core.alias.AliasError'>\n",
      "            <class 'IPython.core.alias.InvalidAliasError'>\n",
      "        <class 'sqlite3.Error'>\n",
      "            <class 'sqlite3.InterfaceError'>\n",
      "            <class 'sqlite3.DatabaseError'>\n",
      "                <class 'sqlite3.InternalError'>\n",
      "                <class 'sqlite3.OperationalError'>\n",
      "                <class 'sqlite3.ProgrammingError'>\n",
      "                <class 'sqlite3.IntegrityError'>\n",
      "                <class 'sqlite3.DataError'>\n",
      "                <class 'sqlite3.NotSupportedError'>\n",
      "        <class 'sqlite3.Warning'>\n",
      "        <class 'IPython.core.interactiveshell.SpaceInInput'>\n",
      "        <class 'xml.dom.DOMException'>\n",
      "            <class 'xml.dom.IndexSizeErr'>\n",
      "            <class 'xml.dom.DomstringSizeErr'>\n",
      "            <class 'xml.dom.HierarchyRequestErr'>\n",
      "            <class 'xml.dom.WrongDocumentErr'>\n",
      "            <class 'xml.dom.InvalidCharacterErr'>\n",
      "            <class 'xml.dom.NoDataAllowedErr'>\n",
      "            <class 'xml.dom.NoModificationAllowedErr'>\n",
      "            <class 'xml.dom.NotFoundErr'>\n",
      "            <class 'xml.dom.NotSupportedErr'>\n",
      "            <class 'xml.dom.InuseAttributeErr'>\n",
      "            <class 'xml.dom.InvalidStateErr'>\n",
      "            <class 'xml.dom.SyntaxErr'>\n",
      "            <class 'xml.dom.InvalidModificationErr'>\n",
      "            <class 'xml.dom.NamespaceErr'>\n",
      "            <class 'xml.dom.InvalidAccessErr'>\n",
      "            <class 'xml.dom.ValidationErr'>\n",
      "        <class 'prompt_toolkit.validation.ValidationError'>\n",
      "        <class 'prompt_toolkit.buffer.EditReadOnlyBuffer'>\n",
      "        <class 'prompt_toolkit.buffer._Retry'>\n",
      "        <class 'prompt_toolkit.layout.layout.InvalidLayoutError'>\n",
      "        <class 'prompt_toolkit.renderer.HeightIsUnknownError'>\n",
      "        <class 'parso.parser.ParserSyntaxError'>\n",
      "        <class 'parso.parser.InternalParseError'>\n",
      "        <class 'parso.python.diff._PositionUpdatingFinished'>\n",
      "        <class 'jedi.inference.helpers.SimpleGetItemNotFound'>\n",
      "        <class 'jedi.inference.utils.UncaughtAttributeError'>\n",
      "        <class 'jedi.inference.base_value.HasNoContext'>\n",
      "        <class 'jedi.inference.arguments.ParamIssue'>\n",
      "        <class 'zipfile.BadZipFile'>\n",
      "        <class 'zipfile.LargeZipFile'>\n",
      "        <class 'jedi.api.exceptions._JediError'>\n",
      "            <class 'jedi.api.exceptions.InternalError'>\n",
      "            <class 'jedi.api.exceptions.WrongVersion'>\n",
      "            <class 'jedi.api.exceptions.RefactoringError'>\n",
      "        <class 'jedi.api.helpers.OnErrorLeaf'>\n",
      "        <class 'jedi.api.environment.InvalidPythonEnvironment'>\n",
      "        <class 'email.errors.MessageError'>\n",
      "            <class 'email.errors.MessageParseError'>\n",
      "                <class 'email.errors.HeaderParseError'>\n",
      "                    <class 'email._header_value_parser._InvalidEwError'>\n",
      "                <class 'email.errors.BoundaryError'>\n",
      "            <class 'email.errors.MultipartConversionError'>\n",
      "            <class 'email.errors.CharsetError'>\n",
      "        <class 'uu.Error'>\n",
      "        <class 'http.client.HTTPException'>\n",
      "            <class 'http.client.NotConnected'>\n",
      "            <class 'http.client.InvalidURL'>\n",
      "            <class 'http.client.UnknownProtocol'>\n",
      "            <class 'http.client.UnknownTransferEncoding'>\n",
      "            <class 'http.client.UnimplementedFileMode'>\n",
      "            <class 'http.client.IncompleteRead'>\n",
      "            <class 'http.client.ImproperConnectionState'>\n",
      "                <class 'http.client.CannotSendRequest'>\n",
      "                <class 'http.client.CannotSendHeader'>\n",
      "                <class 'http.client.ResponseNotReady'>\n",
      "            <class 'http.client.BadStatusLine'>\n",
      "                <class 'http.client.RemoteDisconnected'>\n",
      "            <class 'http.client.LineTooLong'>\n",
      "        <class 'IPython.core.magics.code.InteractivelyDefined'>\n",
      "        <class 'IPython.terminal.embed.KillEmbedded'>\n",
      "        <class 'psutil.Error'>\n",
      "            <class 'psutil.NoSuchProcess'>\n",
      "                <class 'psutil.ZombieProcess'>\n",
      "            <class 'psutil.AccessDenied'>\n",
      "            <class 'psutil.TimeoutExpired'>\n",
      "        <class '_psutil_windows.Error'>\n",
      "        <class '_psutil_windows.TimeoutExpired'>\n",
      "        <class '_psutil_windows.TimeoutAbandoned'>\n",
      "        <class 'tornado.queues.QueueEmpty'>\n",
      "        <class 'tornado.queues.QueueFull'>\n",
      "        <class 'distutils.errors.DistutilsError'>\n",
      "            <class 'distutils.errors.DistutilsModuleError'>\n",
      "            <class 'distutils.errors.DistutilsClassError'>\n",
      "            <class 'distutils.errors.DistutilsGetoptError'>\n",
      "            <class 'distutils.errors.DistutilsArgError'>\n",
      "            <class 'distutils.errors.DistutilsFileError'>\n",
      "            <class 'distutils.errors.DistutilsOptionError'>\n",
      "            <class 'distutils.errors.DistutilsSetupError'>\n",
      "            <class 'distutils.errors.DistutilsPlatformError'>\n",
      "            <class 'distutils.errors.DistutilsExecError'>\n",
      "            <class 'distutils.errors.DistutilsInternalError'>\n",
      "            <class 'distutils.errors.DistutilsTemplateError'>\n",
      "            <class 'distutils.errors.DistutilsByteCompileError'>\n",
      "            <class 'setuptools.errors.RemovedCommandError'>\n",
      "            <class 'setuptools.errors.PackageDiscoveryError'>\n",
      "        <class 'distutils.errors.CCompilerError'>\n",
      "            <class 'distutils.errors.PreprocessError'>\n",
      "            <class 'distutils.errors.CompileError'>\n",
      "            <class 'distutils.errors.LibError'>\n",
      "            <class 'distutils.errors.LinkError'>\n",
      "            <class 'distutils.errors.UnknownFileError'>\n",
      "        <class 'configparser.Error'>\n",
      "            <class 'configparser.NoSectionError'>\n",
      "            <class 'configparser.DuplicateSectionError'>\n",
      "            <class 'configparser.DuplicateOptionError'>\n",
      "            <class 'configparser.NoOptionError'>\n",
      "            <class 'configparser.InterpolationError'>\n",
      "                <class 'configparser.InterpolationMissingOptionError'>\n",
      "                <class 'configparser.InterpolationSyntaxError'>\n",
      "                <class 'configparser.InterpolationDepthError'>\n",
      "            <class 'configparser.ParsingError'>\n",
      "                <class 'configparser.MissingSectionHeaderError'>\n",
      "        <class 'xml.parsers.expat.ExpatError'>\n",
      "        <class 'pywintypes.error'>\n",
      "        <class 'pywintypes.com_error'>\n",
      "        <class 'pythoncom.internal_error'>\n",
      "        <class 'pkg_resources._vendor.pyparsing.ParseBaseException'>\n",
      "            <class 'pkg_resources._vendor.pyparsing.ParseException'>\n",
      "            <class 'pkg_resources._vendor.pyparsing.ParseFatalException'>\n",
      "                <class 'pkg_resources._vendor.pyparsing.ParseSyntaxException'>\n",
      "        <class 'pkg_resources._vendor.pyparsing.RecursiveGrammarException'>\n",
      "        <class 'pkg_resources.ResolutionError'>\n",
      "            <class 'pkg_resources.VersionConflict'>\n",
      "                <class 'pkg_resources.ContextualVersionConflict'>\n",
      "            <class 'pkg_resources.DistributionNotFound'>\n",
      "            <class 'pkg_resources.UnknownExtra'>\n",
      "        <class 'setuptools._vendor.pyparsing.ParseBaseException'>\n",
      "            <class 'setuptools._vendor.pyparsing.ParseException'>\n",
      "            <class 'setuptools._vendor.pyparsing.ParseFatalException'>\n",
      "                <class 'setuptools._vendor.pyparsing.ParseSyntaxException'>\n",
      "        <class 'setuptools._vendor.pyparsing.RecursiveGrammarException'>\n",
      "        <class '_csv.Error'>\n",
      "        <class 'setuptools._vendor.nspektr.Unresolved'>\n",
      "        <class 'unittest.case.SkipTest'>\n",
      "        <class 'unittest.case._ShouldStop'>\n",
      "        <class 'unittest.case._UnexpectedSuccess'>\n",
      "        <class 'xmlrpc.client.Error'>\n",
      "            <class 'xmlrpc.client.ProtocolError'>\n",
      "            <class 'xmlrpc.client.ResponseError'>\n",
      "            <class 'xmlrpc.client.Fault'>\n",
      "        <class '_pydevd_bundle.pydevd_resolver.UnableToResolveVariableException'>\n",
      "        <class '_pydev_bundle.pydev_monkey.InvalidTypeInArgsException'>\n",
      "    <class 'GeneratorExit'>\n",
      "    <class 'SystemExit'>\n",
      "    <class 'KeyboardInterrupt'>\n",
      "    <class 'asyncio.exceptions.CancelledError'>\n",
      "    <class 'pkg_resources._vendor.more_itertools.more.AbortThread'>\n",
      "    <class 'setuptools._vendor.more_itertools.more.AbortThread'>\n",
      "    <class '_pydev_imps._pydev_saved_modules.DebuggerInitializationError'>\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' ' * indent + str(exception_class))\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent+4)\n",
    "\n",
    "print_exception_hierarchy(BaseException)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7f2aaacb",
   "metadata": {},
   "source": [
    "#### Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9e7c087a",
   "metadata": {},
   "source": [
    "#### Answer:\n",
    "The ArithmeticError class in Python is a built-in exception class that is the base class for all errors that occur during arithmetic operations. The ArithmeticError class itself has several built-in subclasses that represent specific types of arithmetic errors. Here are two examples of arithmetic errors that are defined in the ArithmeticError class:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "9ea4076e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "# 1:- ZeroDivisionError: This error is raised when attempting to divide by zero. For example:\n",
    "x = 10\n",
    "y = 0\n",
    "try:\n",
    "    result = x / y\n",
    "except ZeroDivisionError as e:\n",
    "    print(\"Error:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "1c7eae25",
   "metadata": {},
   "outputs": [
    {
     "ename": "OverflowError",
     "evalue": "(34, 'Result too large')",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mOverflowError\u001b[0m                             Traceback (most recent call last)",
      "Input \u001b[1;32mIn [8]\u001b[0m, in \u001b[0;36m<cell line: 3>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# 2 :- OverflowError: This error is raised when the result of an arithmetic operation is too large to be represented by the \u001b[39;00m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;66;03m#data type. For example:\u001b[39;00m\n\u001b[1;32m----> 3\u001b[0m x \u001b[38;5;241m=\u001b[39m \u001b[38;5;241;43m2.0\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m10000\u001b[39;49m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m      5\u001b[0m     y \u001b[38;5;241m=\u001b[39m x \u001b[38;5;241m*\u001b[39m x\n",
      "\u001b[1;31mOverflowError\u001b[0m: (34, 'Result too large')"
     ]
    }
   ],
   "source": [
    "# 2 :- OverflowError: This error is raised when the result of an arithmetic operation is too large to be represented by the \n",
    "#data type. For example:\n",
    "x = 2.0 ** 10000\n",
    "try:\n",
    "    y = x * x\n",
    "except OverflowError as e:\n",
    "    print(\"Error:\", e)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "04e06821",
   "metadata": {},
   "source": [
    "#### Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "95a859d4",
   "metadata": {},
   "source": [
    "#### Answer\n",
    "The LookupError class is a built-in exception class in Python that serves as the base class for all lookup errors. It is used when a lookup operation fails to find the desired item, such as when trying to access an element in a list or dictionary that does not exist.\n",
    "\n",
    "Two common examples of lookup errors in Python are KeyError and IndexError. Here's an explanation of each with an example:\n",
    "\n",
    "KeyError: This error is raised when trying to access a non-existent key in a dictionary. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "4b3481e6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: 'd'\n"
     ]
    }
   ],
   "source": [
    "my_dict = {\"a\": 1, \"b\": 2, \"c\": 3}\n",
    "try:\n",
    "    value = my_dict[\"d\"]\n",
    "except KeyError as e:\n",
    "    print(\"Error:\", e)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9b23651e",
   "metadata": {},
   "source": [
    "IndexError: This error is raised when trying to access an index that is out of range in a list or other sequence. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "49640044",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: list index out of range\n"
     ]
    }
   ],
   "source": [
    "my_list = [1, 2, 3]\n",
    "try:\n",
    "    value = my_list[3]\n",
    "except IndexError as e:\n",
    "    print(\"Error:\", e)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4e27b0d5",
   "metadata": {},
   "source": [
    "#### Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bbf10a6a",
   "metadata": {},
   "source": [
    "#### Answer\n",
    "ImportError is a built-in exception class in Python that is raised when a module or package cannot be imported due to various reasons. For example, ImportError can occur if the module or package is not installed on the system, if the path to the module or package is incorrect, or if the module or package contains syntax errors.\n",
    "\n",
    "there is a subclass of ImportError called ModuleNotFoundError that is raised when a module cannot be found in the system. The ModuleNotFoundError is a more specific and descriptive exception than the generic ImportError.\n",
    "\n",
    "Both ImportError and ModuleNotFoundError are useful exceptions for debugging and troubleshooting when working with Python modules and packages. They provide information about the cause of the import failure and can help us identify and fix the underlying issues."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0da7575f",
   "metadata": {},
   "source": [
    "#### Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3cc619b8",
   "metadata": {},
   "source": [
    "#### Answer\n",
    "\n",
    "Exception handling is an essential aspect of writing robust and reliable Python code. Here are some best practices for exception handling in Python:\n",
    "\n",
    "1. Catch specific exceptions: Instead of catching all exceptions with a generic except block, catch only the specific exceptions that you expect to occur. This approach makes your code more readable, easier to debug, and prevents unexpected exceptions from being hidden.\n",
    "\n",
    "2. Use try-except-finally blocks: Use the try, except, and finally blocks to handle exceptions in your code. The try block contains the code that might raise an exception, the except block handles the exception if one is raised, and the finally block contains code that is executed regardless of whether an exception occurs or not.\n",
    "\n",
    "3. Reraise exceptions: If you catch an exception, but cannot handle it properly, re-raise the exception using the raise statement. This way, the exception will be propagated up the call stack, and the caller can handle it or terminate the program.\n",
    "\n",
    "4. Provide informative error messages: When catching an exception, provide informative error messages that explain what went wrong and how to fix the problem. This information is crucial for debugging and troubleshooting.\n",
    "\n",
    "5. Use context managers: Use context managers, such as the with statement, to automatically handle resources, such as files or network connections, that need to be opened and closed properly.\n",
    "\n",
    "6. Avoid bare except blocks: Avoid using bare except blocks, which catch all exceptions, as they can hide errors and make debugging difficult. Instead, catch only the specific exceptions you expect to occur.\n",
    "\n",
    "7. Handle exceptions close to the source: Handle exceptions as close to the source as possible, where the error occurs. This way, you can provide more detailed error messages and prevent unexpected behavior in your code.\n",
    "\n",
    "8. Document your exceptions: Document the exceptions that your code can raise and provide information about what causes them and how to handle them. This documentation helps other developers who use your code to understand how to use it correctly.\n",
    "\n",
    "By following these best practices, you can write Python code that is more reliable, easier to maintain, and easier to debug when errors occur."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ce370b7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
